// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSzVAcJOdQ2pu8dhpG2lABc34gAT-EQXs',
    appId: '1:192865739775:web:f22d8101c98388e77efdca',
    messagingSenderId: '192865739775',
    projectId: 'justsing-89e3a',
    authDomain: 'justsing-89e3a.firebaseapp.com',
    storageBucket: 'justsing-89e3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU2FW8w1GRkga0ODWUlNn5HasbOWx_o0o',
    appId: '1:192865739775:android:48465fff3cbe5e527efdca',
    messagingSenderId: '192865739775',
    projectId: 'justsing-89e3a',
    storageBucket: 'justsing-89e3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz5IoBnAcT_zRHKu5SHVUkQ5Y2sgxXhig',
    appId: '1:192865739775:ios:10b979f1a8afa29c7efdca',
    messagingSenderId: '192865739775',
    projectId: 'justsing-89e3a',
    storageBucket: 'justsing-89e3a.appspot.com',
    iosClientId: '192865739775-ni44ajb0jqcjtqvsmeruoem5hv82llq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.justsing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz5IoBnAcT_zRHKu5SHVUkQ5Y2sgxXhig',
    appId: '1:192865739775:ios:10b979f1a8afa29c7efdca',
    messagingSenderId: '192865739775',
    projectId: 'justsing-89e3a',
    storageBucket: 'justsing-89e3a.appspot.com',
    iosClientId: '192865739775-ni44ajb0jqcjtqvsmeruoem5hv82llq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.justsing',
  );
}
